### ISSUE TITLE
Отредактировать описание задачи calcbits - Лабораторная работа №1. Задание 2. Вариант 1

### ISSUE THREAD

**Issue by zxzmlk** [alexey-malov/oop#30]

**Comment by zxzmlk** [comment]
![image](https://github.com/user-attachments/assets/b4b509b0-d856-43c7-ad44-0b3c6a129ea9)
Не заметил, что вложенность выходит за пределы задачи, исправляю

**Comment by alexey-malov** [comment]
Принято
