### ISSUE TITLE
Отредактировать описание задачи invert - Лабораторная работа №1. Задание 3. Вариант №2 

### ISSUE THREAD

**Issue by zxzmlk** [alexey-malov/oop#33]

**Comment by alexey-malov** [comment]
Предлагаю убрать в тестах убрать проверку на наличие чего-либо после первых трёх строк.
Иначе на этой проверке студенты будут буксовать.

То есть программа, в которой нет условия после `// Проверяем, нет ли лишних строк в потоке после того, как мы прочитали 3 строки` должна проходить успешно.

**Comment by zxzmlk** [comment]
> Предлагаю убрать в тестах убрать проверку на наличие чего-либо после первых трёх строк. Иначе на этой проверке студенты будут буксовать.
> 
> То есть программа, в которой нет условия после `// Проверяем, нет ли лишних строк в потоке после того, как мы прочитали 3 строки` должна проходить успешно.
> 
> Надо убрать тест 06
> 
> В остальном норм

Убрал

**Comment by alexey-malov** [comment]
Принято
