### ISSUE TITLE
Отредактировать описание задачи dec2bin - Лабораторная работа №1. Задание 2. Вариант №4

### ISSUE THREAD

**Issue by iskolen** [alexey-malov/oop#34]

**Comment by alexey-malov** [comment]
Добавьте в Яндекс.Контест несколько неправильных версий программы, которые не проходят хотя бы один из тестов.
Например, некорректно обрабатывают 0 или отрицательные числа или не обрабатывают какие-то из ошибок.

**Comment by iskolen** [comment]
Добавил 3 неправильные версии программы
