### ISSUE TITLE
Отредактировать описание задачи vector - Лабораторная работа №2. Задание 1. Вариант №5

### ISSUE THREAD

**Issue by iskolen** [alexey-malov/oop#37]

**Comment by alexey-malov** [comment]
Нужно кроме правильного решения в Яндекс.Контекст загрузить еще несколько неправильных, в которых либо не выполнена какая-то часть условия, либо решена неверно.
Неправильные версии программы должны отлавливаться вашими тестами.

**Comment by alexey-malov** [comment]
Проверено
