### ISSUE TITLE
Отредактировать описание задачи Vector-1 - lw №2. Задание 1. Вариант №1

### ISSUE THREAD

**Issue by mrol1114** [alexey-malov/oop#39]
Добавить примеры входных и выходных значений

**Comment by alexey-malov** [comment]
Нужно добавить на платформу Яндекс.Контест несколько некорректных решений, в которых часть условий не реализована или реализована неверно. Например, не выполняется сортировка или числа не так округляются.

Все некорректные программы должны проваливаться на вашем наборе тестов

**Comment by mrol1114** [comment]
Добавлены некорректные программы:
1) fail_processing_all_numbers - включает в сумму отрицательные числа
2) fail_does_not_sort - не сортирует результат
3) fail_dont_process_symbols - не обрабатывает буквы(не валидный ввод)
