### ISSUE TITLE
Добавить примеры для задания TrimBlanks - Лабораторная работа №2. Задание 2. Вариант №1

### ISSUE THREAD

**Issue by mrol1114** [alexey-malov/oop#61]

**Comment by alexey-malov** [comment]
Программа, которая обрабатывает только первую строку, проходит тесты. Однако по условию должно обрабатываться несколько строк
```c++
int main() {
    std::string line;

    // Чтение строк с входного потока до конца ввода
    if (std::getline(std::cin, line)) {
        // Обрезаем пробелы и выводим результат
        std::cout << TrimBlanks(line) << std::endl;
    }
}
```

**Comment by alexey-malov** [comment]
Эталонное решение некорректно использует функцию `isspace` и может вызывать неопределённое поведение.
<https://en.cppreference.com/w/cpp/string/byte/isspace>

> Like all other functions from [<cctype>](https://en.cppreference.com/w/cpp/header/cctype), the behavior of std::isspace is undefined if the argument's value is neither representable as unsigned char nor equal to [EOF](http://en.cppreference.com/w/cpp/io/c). To use these functions safely with plain chars (or signed chars), the argument should first be converted to unsigned char:

```c++
bool my_isspace(char ch)
{
    return std::isspace(static_cast<unsigned char>(ch));
}
```

**Comment by mrol1114** [comment]
> Программа, которая обрабатывает только первую строку, проходит тесты. Однако по условию должно обрабатываться несколько строк
> 
> ```c++
> int main() {
>     std::string line;
> 
>     // Чтение строк с входного потока до конца ввода
>     if (std::getline(std::cin, line)) {
>         // Обрезаем пробелы и выводим результат
>         std::cout << TrimBlanks(line) << std::endl;
>     }
> }
> ```

Доработал 9й тест,  для учета нескольких строк

**Comment by mrol1114** [comment]
> Эталонное решение некорректно использует функцию `isspace` и может вызывать неопределённое поведение. https://en.cppreference.com/w/cpp/string/byte/isspace
> 
> > Like all other functions from , the behavior of std::isspace is undefined if the argument's value is neither representable as unsigned char nor equal to [EOF](http://en.cppreference.com/w/cpp/io/c). To use these functions safely with plain chars (or signed chars), the argument should first be converted to unsigned char:
> 
> ```c++
> bool my_isspace(char ch)
> {
>     return std::isspace(static_cast<unsigned char>(ch));
> }
> ```

исправил
