### ISSUE TITLE
Замечания по тестам программы RemoveExtraSpaces

### ISSUE THREAD

**Issue by alexey-malov** [alexey-malov/oop#73]
По условию задачи программ должна обрабатывать все строки текста, а не только первую.
Однако, эта программа проходит тесты.

```c++
int main() {
    std::string line;
    // Чтение входного потока построчно
    if (std::getline(std::cin, line)) {
        // Выводим строку с удаленными лишними пробелами
        std::cout << RemoveExtraSpaces(line) << std::endl;
    }
}
```

**Comment by alexey-malov** [comment]
Имена файлов неправильных решений должны отражать характер имеющейся ошибки, а не просто "commented line".

**Comment by alexey-malov** [comment]
Если заменить в эталонном решении инициализацию spaceEncountered с false на true, то все тесты пройдут. Нет ли в этом ошибки?

```c++
std::string RemoveExtraSpaces(std::string const& arg) {
    std::string result;
    bool inWord = false;  // Флаг, что мы находимся внутри слова
    bool spaceEncountered = true;  // Флаг, что встретился пробел
```

Кроме того, переменная inWord внутри цикла выставляется в true и больше не меняет своё значение. Выглядит так, будто эталонное решение можно написать оптимальнее

**Comment by rakuzzan** [comment]
Поправил эталонное решение и сделал на его основе несколько мутантов
