### ISSUE TITLE
Замечания по тестам к программе TVSet (+prev channel)

### ISSUE THREAD

**Issue by alexey-malov** [alexey-malov/oop#74]
Неверная реализация CTVSet::GetChannel успешно проходит все тесты:
```c++
int CTVSet::GetChannel() const
{
    return m_selectedChannel;
}
```

Нужно добавить тест для этой ситуации во все задания (так как это базовый функционал)

**Comment by iskolen** [comment]
Отправил Pull Request, с уточнением в условии задачи, чтобы явно указать, что метод GetChannel должен возвращать 0 при выключенном телевизоре.

**Comment by alexey-malov** [comment]
Нужно дополнить описание задачи в контесте списком команд (добавилась команда SelectPreviousChannel) и сообщениями, которые должны выводиться в случае успеха и ошибки

**Comment by alexey-malov** [comment]
> Отправил Pull Request, с уточнением в условии задачи, чтобы явно указать, что метод GetChannel должен возвращать 0 при выключенном телевизоре.

Смержил
