### ISSUE TITLE
Замечания по тестам к задаче ParseExpression

### ISSUE THREAD

**Issue by alexey-malov** [alexey-malov/oop#75]
Тесты проверяют только однозначные числа. Если закомментировать в коде парсинга числа реверсирование строки, программа проходит все тесты.

```c++
        if (isdigit(ch))
        {
            ss.unget();
            ss >> str;

            //if (str.size() > 1)  
            //    reverse(str.begin(), str.end());

            stack.push(stoi(str));
            countOperands++;
        }
```

Добавить этот кейс в неправильные решения и добиться того, чтобы это решение проваливалось на тестах.

**Comment by alexey-malov** [comment]
Программа, не умеющая работать с отрицательными числами, проходит все тесты:


```c++
            stack.push(static_cast<unsigned>(stoi(str)));
```

**Comment by alexey-malov** [comment]
Если закомментировать условие насчёт одного операнда, то все тесты проходят.

```c++
void OperationProcessing(stack<int>& stack, char operation, int countOperands)
{
    if (countOperands == 2)
        OperationProcessingWithTwoOperand(stack, operation);
    else if (/*countOperands == 1 ||*/ countOperands == 3) // <-- вот тут
       OperationProcessingWithThreeOperand(stack, operation);
    else
        while (stack.size() != 1)
            OperationProcessingWithTwoOperand(stack, operation);
}
```

Скорее всего тесты неполны.
Вызов OperationProcessingWithThreeOperand при countOperands == 1 это неопределенное поведение (pop из пустого стека вызовет deque::pop_back, а это UB: https://en.cppreference.com/w/cpp/container/deque/pop_back)
```c++
void OperationProcessingWithThreeOperand(stack<int>& stack, char operation)
{
    int op1 = stack.top();
    stack.pop();
    int op2 = stack.top();
    stack.pop();
    int op3 = stack.top();
    stack.pop();
    if (operation == '+')
    {
        
        stack.push(op1 + op2 + op3);
    }
    else
    {
        stack.push(op1 * op2 * op3);
    }
}
```

Вообще, эталонное решение какое-то очень странное и очень мутное. Рекомендую взять хорошее.

**Comment by rakuzzan** [comment]
Тесты на отрицательные числа проходились по причине того, что я назвал их 010, а не 10. Поправил и добавил 2 теста на двузначные и трехзначные числа. Так же сделал по 4 мутанта на рекурсию и не рекурсию. Только не понял почему у меня 3 мутанта на не рекурсию выдают RuntimeError, хотя вывод 'ERROR' присутствует, то есть программа не должна зациклиться.

**Comment by rakuzzan** [comment]
Разобрался почему RE выпадала при завершении тестирования: программа завершалась с единичным кодом, поменял на 0

**Comment by rakuzzan** [comment]
В ReadMe на гитхабе ничего не менял, тк задача уже полностью описана по моему мнению. Или надо что-то подправить? Просто вы в таблице перевели задачу в "Не начато"

**Comment by alexey-malov** [comment]
> Тесты на отрицательные числа проходились по причине того, что я назвал их 010, а не 10. Поправил и добавил 2 теста на двузначные и трехзначные числа. Так же сделал по 4 мутанта на рекурсию и не рекурсию. Только не понял почему у меня 3 мутанта на не рекурсию выдают RuntimeError, хотя вывод 'ERROR' присутствует, то есть программа не должна зациклиться.

При запуске на платформе Яндекс.Contest выход приложения с ненулевым кодом возврата вызывает Runtime Error.

![image](https://github.com/user-attachments/assets/d64bf385-88aa-42e4-8d96-87b4d683ad40)
